---
title: "In-Class_Ex04"
description: |
  A short description of the post.
author:
  - name: Wayne Ng
    url: https://www.linkedin.com/in/wayne-ng-56331b208
date: 09-06-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Installing R packages 
- sf is mainly used for importing geospatial data.
- raster is for handling raster-based geospatial data
- tmap is to plot
- spatstat is in ppp format

```{r}
packages = c('maptools', 'sf', 'raster','spatstat', 'tmap', 'tidyverse')
for (p in packages){
if(!require(p, character.only = T)){
install.packages(p)
}
library(p,character.only = T)
}
```
# Importing Geospatial Data
```{r echo=TRUE}
childcare_sf <- st_read("data/child-care-services-geojson.geojson") %>%
  st_transform(crs = 3414)
```

```{r echo=TRUE}
sg_sf <- st_read(dsn = "data", layer="CostalOutline")
```
```{r echo=TRUE}
mpsz_sf <- st_read(dsn = "data", 
                layer = "MP14_SUBZONE_WEB_PL")
```
# Importing RDS
```{r echo=TRUE}
childcare <- read_rds("data/rds/childcare.rds")
CHAS <- read_rds("data/rds/CHAS.rds")
```

```{r echo=TRUE}
CHAS_sf <- st_as_sf(CHAS, coords = c("X_COORDINATE","Y_COORDINATE" ), crs=3414)
```

```{r echo=TRUE}
childcare$Lat <- as.numeric(childcare$Lat)
childcare$Lng <- as.numeric(childcare$Lng)
childcare_sf <- st_as_sf(childcare, coords = c("Lng", "Lat"), crs=4326) %>%
  st_transform(crs = 3414)
```
```{r echo=TRUE}
childcare <- as_Spatial(childcare_sf)
CHAS <- as_Spatial(CHAS_sf)
mpsz <- as_Spatial(mpsz_sf)
sg <- as_Spatial(sg_sf)
```
```{r echo=TRUE}
childcare_sp <- as(childcare, "SpatialPoints")
CHAS_sp <- as(CHAS, "SpatialPoints")
sg_sp <- as(sg, "SpatialPolygons")
```
```{r echo=TRUE}
childcare_ppp <- as(childcare_sp, "ppp")
CHAS_ppp <- as(CHAS_sp, "ppp")
```


# 

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


